### ISSUE TITLE
Create path if not exists

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/good-file#55]
Why doesn't good-file try to create the path before adding a log file to it? Seems like a usefull feature.

**Comment by arb** [comment]
It creates the file, but not the path. Probably because I assume if you are running this type of thing in production you are running the Node process with limited privileges so it might not be allowed to create paths and files. Also, the added complexity of accidentally blowing an entire path or folder away is a little scary.

**Comment by AdriVanHoudt** [comment]
I get the privilege point but trying never hurts. And what do you mean with blowing an entire path? It comes down to checking if the path exists and if not creating it, no need to override or something

**Comment by brandonramirez** [comment]
Agreed, this would simply usage and deployment.  I like software that handles its own pre-reqs whenever possible, like creating directories that it cares about.

**Comment by damirv** [comment]
+1

**Comment by arb** [comment]
I'll take a PR for this.

**Comment by brandonramirez** [comment]
Thank you for implementing this!

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by nathanbuchar** [comment]
You got it! :v:
