### ISSUE TITLE
Add support for formatting the log lines with custom format

### ISSUE THREAD

**Issue by mik01aj** [hapijs/good-file#66]
It seems bizzare to me that the only supported output format is JSON. JSON with timestamps as integers is NOT human readable.

Or maybe there is some other way to get a human-readable log in a file?

**Comment by arb** [comment]
The original intent of this module was to spit out unformatted data to a file that is then imported into another reporting system. It wasn't really designed to be viewed by humans directly. 

That being said, I'll take a PR add moment.js support for the time string.

**Comment by mik01aj** [comment]
And how about adding the possibility to add a transformation function to config (it would transform the event object into a nice string)?

**Comment by arb** [comment]
Let's do one thing at a time.

**Comment by gergoerdosi** [comment]
I looked into this because we need a readable time format too. The solution is not straightforward because the data object is frozen, so values can't be modified:

https://github.com/hapijs/good/blob/master/lib/utils.js#L63

Should we clone the data object an "unfreeze" it, or should we use `Object.seal()` instead of `Object.freeze()`?

**Comment by arb** [comment]
I don't really want to change the `Object.freeze` because people kept changing the objects and causing reporting bugs in other reporter objects. We could add another transform stream to the pipeline as a possibility?

**Comment by gergoerdosi** [comment]
Yes, `freeze` makes sense. We could add a transform stream, but the stream receives the frozen `data` object:

https://github.com/hapijs/good-squeeze/blob/master/lib/safe-json.js#L31

So we can't just do `data.time = moment(...)` because it raises an error (object property can't be modified). Unfreezing is not easy, all properties need to be copied recursively: http://stackoverflow.com/questions/19293321/opposite-of-object-freeze-or-object-seal-in-javascript

**Comment by gergoerdosi** [comment]
Actually, `Hoek.clone()` works, the cloned object is not frozen. I will work on a PR then and we can take it from there.

**Comment by arb** [comment]
Clone is a very expensive operation. If you're logging requests with good-file, you're going to be cloning thousands and thousands of objects... 

We could include an editable copy of the data object as well as the frozen one? We could also try to send a clean copy of data to each reporter so changes to the data object doesn't have any downstream impacts.

**Comment by gergoerdosi** [comment]
I think sending an editable copy in addition to the frozen one wouldn't work, because we had the same problem then, reporters may modify that object and the other reporter may receive a different one.

I like the second approach, sending a clean copy of data to each reporter. But how would you achieve that without cloning?

**Comment by gergoerdosi** [comment]
@arb Any news on this? An editable copy sounds good, but I think doing a clone is inevitable at some point. If you don't want to do the cloning in good or good-file, I will just create a custom reporter which does that.

**Comment by arb** [comment]
Nothing new to add. I'm not sure how to send out a different instance when you `push` data through a stream and I don't want to drop the `Freeze` aspect. I'm kicking around ideas for dealing with this, but it's not going to happen any time soon.

If you're in a hurry, a custom reporter will be your best bet.

**Comment by gergoerdosi** [comment]
Ok, will do that then. Thanks.

**Comment by bencooling** [comment]
> Or maybe there is some other way to get a human-readable log in a file?

good-human.js
```
'use strict';

const GoodFile = require('good-file');

class GoodHuman extends GoodFile {
  _write(data, encoding, callback) {
    super._write(new Buffer(JSON.parse(data.toString()).data + '\r\n'), encoding, callback);
  }
}

module.exports = GoodHuman;
```

index.js/manifest.js
```
  reporters: {
    log: [
      { module: 'good-squeeze', name: 'Squeeze', args: [{ log: 'info' }] },
      { module: 'good-squeeze', name: 'SafeJson' },
      { module: path.join(__dirname, './good-human.js'), args: ['./human.log'] },
    ],
   ...
```

Now this line:
`server.log(['info'], 'Server started at ' + server.info.uri);`

Will look like this in the log file: 
`Server running at: http://localhost:52471`
